package com.agrios.platform.cropcycle.domain;

public enum CropCycleStatus {
    PLANNED, ACTIVATED, LAND_PREPARATION, SOWN, ESTABLISHED, GROWING,
    REPRODUCTIVE, HARVEST_READY, HARVESTED, POST_HARVEST, CLOSED,
    CANCELLED, FAILED_ESTABLISHMENT, RESOWING, PARTIAL_CROP_LOSS,
    TOTAL_CROP_LOSS, ABANDONED
}
