package com.agrios.platform.serviceappointment.api;
import com.agrios.platform.common.web.TenantContextResolver; import com.agrios.platform.serviceappointment.application.ServiceAppointmentService; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import java.nio.charset.StandardCharsets; import java.time.Instant; import java.util.*; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1") public class ServiceAppointmentController {private final ServiceAppointmentService service;private final TenantContextResolver tenants;public ServiceAppointmentController(ServiceAppointmentService s,TenantContextResolver t){service=s;tenants=t;}
 @PostMapping("/service-providers") Map<String,UUID> create(@Valid @RequestBody ServiceAppointmentDtos.ProviderRequest b,HttpServletRequest r){return Map.of("providerId",service.createProvider(tenants.resolve(r).tenantId(),b));}
 @GetMapping("/service-providers") List<ServiceAppointmentDtos.ProviderResponse> search(@RequestParam(required=false) String type,HttpServletRequest r){return service.search(tenants.resolve(r).tenantId(),type);}
 @PostMapping("/service-providers/{providerId}/availability") Map<String,UUID> availability(@PathVariable UUID providerId,@Valid @RequestBody ServiceAppointmentDtos.AvailabilityRequest b,HttpServletRequest r){return Map.of("availabilityId",service.addAvailability(tenants.resolve(r).tenantId(),providerId,b));}
 @GetMapping("/service-providers/{providerId}/availability") List<ServiceAppointmentDtos.AvailabilityResponse> availability(@PathVariable UUID providerId,@RequestParam Instant from,@RequestParam Instant to,HttpServletRequest r){return service.availability(tenants.resolve(r).tenantId(),providerId,from,to);}
 @PostMapping("/service-appointments") ServiceAppointmentDtos.AppointmentResponse book(@Valid @RequestBody ServiceAppointmentDtos.AppointmentRequest b,HttpServletRequest r){return service.book(tenants.resolve(r).tenantId(),actorId(),b);}
 @PostMapping("/service-appointments/{id}/status") ServiceAppointmentDtos.AppointmentResponse status(@PathVariable UUID id,@Valid @RequestBody ServiceAppointmentDtos.StatusRequest b,HttpServletRequest r){return service.transition(tenants.resolve(r).tenantId(),id,b);}
 @PostMapping("/service-appointments/{id}/visit-note") void note(@PathVariable UUID id,@Valid @RequestBody ServiceAppointmentDtos.VisitNoteRequest b,HttpServletRequest r){service.addVisitNote(tenants.resolve(r).tenantId(),id,b);}
 @PostMapping("/service-appointments/{id}/review") void review(@PathVariable UUID id,@Valid @RequestBody ServiceAppointmentDtos.ReviewRequest b,HttpServletRequest r){service.review(tenants.resolve(r).tenantId(),id,b);}
 @GetMapping("/farmers/{farmerId}/service-appointments") List<ServiceAppointmentDtos.AppointmentResponse> farmer(@PathVariable UUID farmerId,HttpServletRequest r){return service.farmerAppointments(tenants.resolve(r).tenantId(),farmerId);}
 @GetMapping("/service-providers/{providerId}/dashboard") ServiceAppointmentDtos.ProviderDashboard dashboard(@PathVariable UUID providerId,@RequestParam Instant from,@RequestParam Instant to,HttpServletRequest r){return service.dashboard(tenants.resolve(r).tenantId(),providerId,from,to);}
 private UUID actorId(){return UUID.nameUUIDFromBytes("development-actor".getBytes(StandardCharsets.UTF_8));}}
