package com.agrios.platform.inventory.application;
import com.agrios.platform.common.exception.*; import com.agrios.platform.farm.domain.FarmRepository; import com.agrios.platform.inventory.api.InventoryDtos; import com.agrios.platform.inventory.domain.*; import java.math.BigDecimal; import java.time.LocalDate; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class InventoryService {private final InventoryItemRepository items;private final InventoryLotRepository lots;private final StockMovementRepository movements;private final FarmRepository farms;
 public InventoryService(InventoryItemRepository i,InventoryLotRepository l,StockMovementRepository m,FarmRepository f){items=i;lots=l;movements=m;farms=f;}
 @Transactional public InventoryDtos.ItemResponse create(UUID tenant,UUID actor,InventoryDtos.CreateItemRequest r){farms.findByIdAndTenantId(r.farmId(),tenant).orElseThrow(()->new ResourceNotFoundException("FARM_NOT_FOUND","Farm not found."));if(items.existsByTenantIdAndFarmIdAndItemCode(tenant,r.farmId(),r.itemCode()))throw new BusinessException("INVENTORY_ITEM_CODE_EXISTS","Inventory item code already exists.",409);return InventoryDtos.ItemResponse.from(items.save(InventoryItemEntity.create(tenant,r.farmId(),r.itemCode(),r.itemName(),r.category(),r.baseUnit(),r.reorderLevel(),actor)));}
 @Transactional public InventoryDtos.LotResponse receive(UUID tenant,UUID actor,UUID itemId,InventoryDtos.ReceiveRequest r){var item=require(tenant,itemId);String key="RECEIPT:"+itemId+":"+r.lotReference();if(movements.existsByTenantIdAndIdempotencyKey(tenant,key))throw new BusinessException("DUPLICATE_STOCK_RECEIPT","Stock receipt already recorded.",409);var lot=lots.save(InventoryLotEntity.create(tenant,itemId,r.lotReference(),r.receivedDate(),r.expiryDate(),r.quantity(),r.unitCost(),r.currency(),r.supplierReference()));item.increase(r.quantity(),actor);movements.save(StockMovementEntity.create(tenant,itemId,lot.id(),"RECEIPT",r.quantity(),item.baseUnit(),r.receivedDate(),"INVENTORY","INVENTORY_LOT",lot.id(),key,r.notes(),actor));return InventoryDtos.LotResponse.from(lot);}
 @Transactional public InventoryDtos.ItemResponse adjust(UUID tenant,UUID actor,UUID itemId,InventoryDtos.AdjustRequest r){var item=require(tenant,itemId);boolean in="IN".equalsIgnoreCase(r.direction());if(!in&&!"OUT".equalsIgnoreCase(r.direction()))throw new BusinessException("INVALID_ADJUSTMENT_DIRECTION","Direction must be IN or OUT.",422);String key=r.idempotencyKey()==null||r.idempotencyKey().isBlank()?"ADJUST:"+UUID.randomUUID():r.idempotencyKey();if(movements.existsByTenantIdAndIdempotencyKey(tenant,key))throw new BusinessException("DUPLICATE_STOCK_MOVEMENT","Stock movement already recorded.",409);try{if(in)item.increase(r.quantity(),actor);else item.decrease(r.quantity(),actor);}catch(IllegalStateException e){throw new BusinessException("INSUFFICIENT_STOCK",e.getMessage(),422);}movements.save(StockMovementEntity.create(tenant,itemId,null,in?"ADJUSTMENT_IN":"ADJUSTMENT_OUT",r.quantity(),item.baseUnit(),LocalDate.now(),"INVENTORY","MANUAL_ADJUSTMENT",null,key,r.reason(),actor));return InventoryDtos.ItemResponse.from(item);}
 @Transactional(readOnly=true) public List<InventoryDtos.ItemResponse> list(UUID tenant,UUID farmId){return items.findByTenantIdAndFarmIdAndActiveTrueOrderByItemName(tenant,farmId).stream().map(InventoryDtos.ItemResponse::from).toList();}
 @Transactional(readOnly=true) public List<InventoryDtos.LotResponse> expiring(UUID tenant,LocalDate from,LocalDate to){return lots.findByTenantIdAndExpiryDateBetweenAndQuantityAvailableGreaterThanOrderByExpiryDateAsc(tenant,from,to,BigDecimal.ZERO).stream().map(InventoryDtos.LotResponse::from).toList();}
 private InventoryItemEntity require(UUID tenant,UUID id){return items.findByIdAndTenantId(id,tenant).orElseThrow(()->new ResourceNotFoundException("INVENTORY_ITEM_NOT_FOUND","Inventory item not found."));}
}
