package com.agrios.platform.serviceappointment.application;
import com.agrios.platform.advisory.domain.ExpertProfileRepository; import com.agrios.platform.common.exception.*; import com.agrios.platform.serviceappointment.api.ServiceAppointmentDtos; import com.agrios.platform.serviceappointment.domain.*; import com.fasterxml.jackson.core.JsonProcessingException; import com.fasterxml.jackson.databind.ObjectMapper; import java.time.Instant; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class ServiceAppointmentService {
 private static final Set<String> TYPES=Set.of("VET","AGRONOMIST","CROP_EXPERT","SOIL_EXPERT","IRRIGATION_EXPERT","FEED_SELLER","INPUT_SELLER","EQUIPMENT_SERVICE","OTHER"); private static final Set<String> MODES=Set.of("IN_PERSON","REMOTE","BOTH");
 private final ServiceProviderRepository providers; private final ProviderAvailabilityRepository availability; private final AppointmentRepository appointments; private final AppointmentVisitNoteRepository notes; private final ProviderReviewRepository reviews; private final ExpertProfileRepository experts; private final ObjectMapper mapper;
 public ServiceAppointmentService(ServiceProviderRepository p,ProviderAvailabilityRepository a,AppointmentRepository ap,AppointmentVisitNoteRepository n,ProviderReviewRepository r,ExpertProfileRepository e,ObjectMapper m){providers=p;availability=a;appointments=ap;notes=n;reviews=r;experts=e;mapper=m;}
 @Transactional public UUID createProvider(UUID tenantId,ServiceAppointmentDtos.ProviderRequest r){if(!TYPES.contains(r.providerType()))throw new BusinessException("INVALID_PROVIDER_TYPE","Unsupported provider type.",422);if(!MODES.contains(r.consultationMode()))throw new BusinessException("INVALID_CONSULTATION_MODE","Unsupported consultation mode.",422);if(r.expertProfileId()!=null)experts.findByIdAndTenantId(r.expertProfileId(),tenantId).orElseThrow(()->new ResourceNotFoundException("EXPERT_NOT_FOUND","Expert profile not found."));return providers.save(ServiceProviderEntity.create(tenantId,r.expertProfileId(),r.userAccountId(),r.providerType(),r.displayName(),r.organizationName(),r.phoneNumber(),r.emailAddress(),r.registrationReference(),json(r.serviceAreaCodes()==null?Set.of():r.serviceAreaCodes()),json(r.languageCodes()==null?Set.of():r.languageCodes()),json(r.serviceCodes()==null?Set.of():r.serviceCodes()),r.consultationMode())).id();}
 @Transactional(readOnly=true) public List<ServiceAppointmentDtos.ProviderResponse> search(UUID tenantId,String type){var list=type==null||type.isBlank()?providers.findByTenantIdAndStatusOrderByAverageRatingDesc(tenantId,"ACTIVE"):providers.findByTenantIdAndProviderTypeAndStatusOrderByAverageRatingDesc(tenantId,type,"ACTIVE");return list.stream().map(ServiceAppointmentDtos.ProviderResponse::from).toList();}
 @Transactional public UUID addAvailability(UUID tenantId,UUID providerId,ServiceAppointmentDtos.AvailabilityRequest r){requireProvider(tenantId,providerId);if(!r.endAt().isAfter(r.startAt()))throw new BusinessException("INVALID_AVAILABILITY_RANGE","End time must be after start time.",422);return availability.save(ProviderAvailabilityEntity.create(tenantId,providerId,r.startAt(),r.endAt(),r.mode(),r.locationText(),r.capacity())).id();}
 @Transactional(readOnly=true) public List<ServiceAppointmentDtos.AvailabilityResponse> availability(UUID tenantId,UUID providerId,Instant from,Instant to){requireProvider(tenantId,providerId);return availability.findByTenantIdAndProviderIdAndStartAtBetweenAndStatusOrderByStartAt(tenantId,providerId,from,to,"AVAILABLE").stream().map(ServiceAppointmentDtos.AvailabilityResponse::from).toList();}
 @Transactional public ServiceAppointmentDtos.AppointmentResponse book(UUID tenantId,UUID actor,ServiceAppointmentDtos.AppointmentRequest r){var provider=requireProvider(tenantId,r.providerId());if(!"ACTIVE".equals(provider.status()))throw new BusinessException("PROVIDER_NOT_ACTIVE","Provider is not active.",422);if(!r.scheduledEndAt().isAfter(r.scheduledStartAt()))throw new BusinessException("INVALID_APPOINTMENT_RANGE","End time must be after start time.",422);ProviderAvailabilityEntity slot=null;if(r.availabilityId()!=null){slot=availability.findByIdAndTenantId(r.availabilityId(),tenantId).orElseThrow(()->new ResourceNotFoundException("AVAILABILITY_NOT_FOUND","Availability slot not found."));if(!slot.providerId().equals(r.providerId()))throw new BusinessException("AVAILABILITY_PROVIDER_MISMATCH","Availability does not belong to provider.",422);if(slot.bookedCount()>=slot.capacity())throw new ConflictException("AVAILABILITY_FULL","Availability slot is full.");slot.book();}return ServiceAppointmentDtos.AppointmentResponse.from(appointments.save(AppointmentEntity.create(tenantId,r.providerId(),r.availabilityId(),r.farmerId(),r.farmId(),r.fieldId(),r.cropCycleId(),r.subjectType(),r.subjectReferenceId(),r.appointmentType(),r.mode(),r.scheduledStartAt(),r.scheduledEndAt(),r.locationText(),r.problemSummary(),actor)));}
 @Transactional public ServiceAppointmentDtos.AppointmentResponse transition(UUID tenantId,UUID id,ServiceAppointmentDtos.StatusRequest r){var a=requireAppointment(tenantId,id);var allowed=Map.of("REQUESTED",Set.of("CONFIRMED","REJECTED","CANCELLED"),"CONFIRMED",Set.of("IN_PROGRESS","CANCELLED","NO_SHOW"),"IN_PROGRESS",Set.of("COMPLETED","CANCELLED"));if(!allowed.getOrDefault(a.status(),Set.of()).contains(r.status()))throw new BusinessException("INVALID_APPOINTMENT_TRANSITION","Appointment status transition is not allowed.",422);if("COMPLETED".equals(r.status()))a.complete(r.providerNotes());else a.transition(r.status(),r.reason());return ServiceAppointmentDtos.AppointmentResponse.from(a);}
 @Transactional public void addVisitNote(UUID tenantId,UUID id,ServiceAppointmentDtos.VisitNoteRequest r){var a=requireAppointment(tenantId,id);if(!a.providerId().equals(r.providerId()))throw new BusinessException("APPOINTMENT_PROVIDER_MISMATCH","Provider is not assigned to appointment.",422);if(!"COMPLETED".equals(a.status()))throw new BusinessException("APPOINTMENT_NOT_COMPLETED","Visit note can be added only after completion.",422);if(notes.existsByAppointmentId(id))throw new ConflictException("VISIT_NOTE_ALREADY_EXISTS","Visit note already exists.");notes.save(AppointmentVisitNoteEntity.create(id,r.providerId(),r.diagnosisSummary(),r.recommendationText(),json(r.prescriptionDetails()==null?List.of():r.prescriptionDetails()),r.followUpRequired(),r.followUpDueAt(),json(r.attachmentReferences()==null?List.of():r.attachmentReferences())));}
 @Transactional public void review(UUID tenantId,UUID id,ServiceAppointmentDtos.ReviewRequest r){var a=requireAppointment(tenantId,id);if(!a.farmerId().equals(r.farmerId()))throw new BusinessException("APPOINTMENT_FARMER_MISMATCH","Farmer does not own appointment.",422);if(!"COMPLETED".equals(a.status()))throw new BusinessException("APPOINTMENT_NOT_COMPLETED","Only completed appointments can be reviewed.",422);if(reviews.existsByAppointmentId(id))throw new ConflictException("PROVIDER_REVIEW_ALREADY_EXISTS","Review already exists.");reviews.save(ProviderReviewEntity.create(tenantId,id,a.providerId(),r.farmerId(),r.rating(),r.reviewText()));var all=reviews.findByProviderIdAndStatus(a.providerId(),"PUBLISHED");var avg=all.stream().mapToInt(ProviderReviewEntity::rating).average().orElse(0);requireProvider(tenantId,a.providerId()).refreshRating(avg,all.size());}
 @Transactional(readOnly=true) public List<ServiceAppointmentDtos.AppointmentResponse> farmerAppointments(UUID tenantId,UUID farmerId){return appointments.findByTenantIdAndFarmerIdOrderByScheduledStartAtDesc(tenantId,farmerId).stream().map(ServiceAppointmentDtos.AppointmentResponse::from).toList();}
 @Transactional(readOnly=true) public ServiceAppointmentDtos.ProviderDashboard dashboard(UUID tenantId,UUID providerId,Instant from,Instant to){requireProvider(tenantId,providerId);var upcoming=appointments.findByTenantIdAndProviderIdAndScheduledStartAtBetweenOrderByScheduledStartAt(tenantId,providerId,from,to);return new ServiceAppointmentDtos.ProviderDashboard(appointments.countByTenantIdAndProviderIdAndStatus(tenantId,providerId,"REQUESTED"),appointments.countByTenantIdAndProviderIdAndStatus(tenantId,providerId,"CONFIRMED"),appointments.countByTenantIdAndProviderIdAndStatus(tenantId,providerId,"IN_PROGRESS"),appointments.countByTenantIdAndProviderIdAndStatus(tenantId,providerId,"COMPLETED"),upcoming.stream().map(ServiceAppointmentDtos.AppointmentResponse::from).toList());}
 private ServiceProviderEntity requireProvider(UUID tenantId,UUID id){return providers.findByIdAndTenantId(id,tenantId).orElseThrow(()->new ResourceNotFoundException("SERVICE_PROVIDER_NOT_FOUND","Service provider not found."));} private AppointmentEntity requireAppointment(UUID tenantId,UUID id){return appointments.findByIdAndTenantId(id,tenantId).orElseThrow(()->new ResourceNotFoundException("APPOINTMENT_NOT_FOUND","Appointment not found."));} private String json(Object o){try{return mapper.writeValueAsString(o);}catch(JsonProcessingException e){throw new BusinessException("JSON_SERIALIZATION_FAILED","Unable to serialize service data.",500);}}
}
